version: '3'

services:
  node-backend-dev:
    build:
      context: .
      dockerfile: node.dev.dockerfile
    volumes:
      - ./src:/usr/src
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  db: 
    image: postgres:16.1-alpine
    restart: on-failure
    env_file: .env.db
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  react-frontend-dev:
    build:
      context: ./client
      dockerfile: react.dev.dockerfile
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - node-backend-dev

volumes: 
  postgres-data:

networks:
  app-network:
    driver: bridge

